// Copyright 2012-2025 The Rust Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution and at
// http://rust-lang.org/COPYRIGHT.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

// NOTE: The following code was generated by "scripts/unicode.py", do not edit directly
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct WidthInfo(u16);

const LIGATURE_TRANSPARENT_MASK: u16 = 0b0010_0000_0000_0000;

impl WidthInfo {
    /// No special handling necessary
    pub(crate) const DEFAULT: Self = Self(0);
    pub(crate) const LINE_FEED: Self = Self(0b0000000000000001);
    pub(crate) const EMOJI_MODIFIER: Self = Self(0b0000000000000010);
    pub(crate) const REGIONAL_INDICATOR: Self = Self(0b0000000000000011);
    pub(crate) const SEVERAL_REGIONAL_INDICATOR: Self = Self(0b0000000000000100);
    pub(crate) const EMOJI_PRESENTATION: Self = Self(0b0000000000000101);
    pub(crate) const ZWJ_EMOJI_PRESENTATION: Self = Self(0b0001000000000110);
    pub(crate) const VS16_ZWJ_EMOJI_PRESENTATION: Self = Self(0b1001000000000110);
    pub(crate) const KEYCAP_ZWJ_EMOJI_PRESENTATION: Self = Self(0b0001000000000111);
    pub(crate) const VS16_KEYCAP_ZWJ_EMOJI_PRESENTATION: Self = Self(0b1001000000000111);
    pub(crate) const REGIONAL_INDICATOR_ZWJ_PRESENTATION: Self = Self(0b0000000000001001);
    pub(crate) const EVEN_REGIONAL_INDICATOR_ZWJ_PRESENTATION: Self = Self(0b0000000000001010);
    pub(crate) const ODD_REGIONAL_INDICATOR_ZWJ_PRESENTATION: Self = Self(0b0000000000001011);
    pub(crate) const TAG_END_ZWJ_EMOJI_PRESENTATION: Self = Self(0b0000000000010000);
    pub(crate) const TAG_D1_END_ZWJ_EMOJI_PRESENTATION: Self = Self(0b0000000000010001);
    pub(crate) const TAG_D2_END_ZWJ_EMOJI_PRESENTATION: Self = Self(0b0000000000010010);
    pub(crate) const TAG_D3_END_ZWJ_EMOJI_PRESENTATION: Self = Self(0b0000000000010011);
    pub(crate) const TAG_A1_END_ZWJ_EMOJI_PRESENTATION: Self = Self(0b0000000000011001);
    pub(crate) const TAG_A2_END_ZWJ_EMOJI_PRESENTATION: Self = Self(0b0000000000011010);
    pub(crate) const TAG_A3_END_ZWJ_EMOJI_PRESENTATION: Self = Self(0b0000000000011011);
    pub(crate) const TAG_A4_END_ZWJ_EMOJI_PRESENTATION: Self = Self(0b0000000000011100);
    pub(crate) const TAG_A5_END_ZWJ_EMOJI_PRESENTATION: Self = Self(0b0000000000011101);
    pub(crate) const TAG_A6_END_ZWJ_EMOJI_PRESENTATION: Self = Self(0b0000000000011110);
    pub(crate) const KIRAT_RAI_VOWEL_SIGN_E: Self = Self(0b0000000000100000);
    pub(crate) const KIRAT_RAI_VOWEL_SIGN_AI: Self = Self(0b0000000000100001);
    pub(crate) const VARIATION_SELECTOR_1_2_OR_3: Self = Self(0b0000001000000000);
    pub(crate) const VARIATION_SELECTOR_15: Self = Self(0b0100000000000000);
    pub(crate) const VARIATION_SELECTOR_16: Self = Self(0b1000000000000000);
    pub(crate) const JOINING_GROUP_ALEF: Self = Self(0b0011000011111111);
    #[cfg(feature = "cjk")]
    pub(crate) const COMBINING_LONG_SOLIDUS_OVERLAY: Self = Self(0b0011110011111111);
    #[cfg(feature = "cjk")]
    pub(crate) const SOLIDUS_OVERLAY_ALEF: Self = Self(0b0011100011111111);
    pub(crate) const HEBREW_LETTER_LAMED: Self = Self(0b0011100000000000);
    pub(crate) const ZWJ_HEBREW_LETTER_LAMED: Self = Self(0b0011110000000000);
    pub(crate) const BUGINESE_LETTER_YA: Self = Self(0b0011100000000001);
    pub(crate) const ZWJ_BUGINESE_LETTER_YA: Self = Self(0b0011110000000001);
    pub(crate) const BUGINESE_VOWEL_SIGN_I_ZWJ_LETTER_YA: Self = Self(0b0011110000000010);
    pub(crate) const TIFINAGH_CONSONANT: Self = Self(0b0011100000000011);
    pub(crate) const ZWJ_TIFINAGH_CONSONANT: Self = Self(0b0011110000000011);
    pub(crate) const TIFINAGH_JOINER_CONSONANT: Self = Self(0b0011110000000100);
    pub(crate) const LISU_TONE_LETTER_MYA_NA_JEU: Self = Self(0b0011110000000101);
    pub(crate) const OLD_TURKIC_LETTER_ORKHON_I: Self = Self(0b0011100000000110);
    pub(crate) const ZWJ_OLD_TURKIC_LETTER_ORKHON_I: Self = Self(0b0011110000000110);
    pub(crate) const KHMER_COENG_ELIGIBLE_LETTER: Self = Self(0b0011110000000111);

    /// Whether this width mode is ligature_transparent
    /// (has 5th MSB set.)
    pub(crate) fn is_ligature_transparent(self) -> bool {
        (self.0 & 0b0000_1000_0000_0000) == 0b0000_1000_0000_0000
    }

    /// Sets 6th MSB.
    pub(crate) fn set_zwj_bit(self) -> Self {
        Self(self.0 | 0b0000_0100_0000_0000)
    }

    /// Has top bit set
    pub(crate) fn is_emoji_presentation(self) -> bool {
        (self.0 & WidthInfo::VARIATION_SELECTOR_16.0) == WidthInfo::VARIATION_SELECTOR_16.0
    }

    pub(crate) fn is_zwj_emoji_presentation(self) -> bool {
        (self.0 & 0b1011_0000_0000_0000) == 0b1001_0000_0000_0000
    }

    /// Set top bit
    pub(crate) fn set_emoji_presentation(self) -> Self {
        if (self.0 & LIGATURE_TRANSPARENT_MASK) == LIGATURE_TRANSPARENT_MASK
            || (self.0 & 0b1001_0000_0000_0000) == 0b0001_0000_0000_0000
        {
            Self(
                self.0
                    | WidthInfo::VARIATION_SELECTOR_16.0
                        & !WidthInfo::VARIATION_SELECTOR_15.0
                        & !WidthInfo::VARIATION_SELECTOR_1_2_OR_3.0,
            )
        } else {
            Self::VARIATION_SELECTOR_16
        }
    }

    /// Clear top bit
    pub(crate) fn unset_emoji_presentation(self) -> Self {
        if (self.0 & LIGATURE_TRANSPARENT_MASK) == LIGATURE_TRANSPARENT_MASK {
            Self(self.0 & !WidthInfo::VARIATION_SELECTOR_16.0)
        } else {
            Self::DEFAULT
        }
    }

    /// Has 2nd bit set
    pub(crate) fn is_text_presentation(self) -> bool {
        (self.0 & WidthInfo::VARIATION_SELECTOR_15.0) == WidthInfo::VARIATION_SELECTOR_15.0
    }

    /// Set 2nd bit
    pub(crate) fn set_text_presentation(self) -> Self {
        if (self.0 & LIGATURE_TRANSPARENT_MASK) == LIGATURE_TRANSPARENT_MASK {
            Self(
                self.0
                    | WidthInfo::VARIATION_SELECTOR_15.0
                        & !WidthInfo::VARIATION_SELECTOR_16.0
                        & !WidthInfo::VARIATION_SELECTOR_1_2_OR_3.0,
            )
        } else {
            Self(WidthInfo::VARIATION_SELECTOR_15.0)
        }
    }

    /// Clear 2nd bit
    pub(crate) fn unset_text_presentation(self) -> Self {
        Self(self.0 & !WidthInfo::VARIATION_SELECTOR_15.0)
    }

    /// Has 7th bit set
    pub(crate) fn is_vs1_2_3(self) -> bool {
        (self.0 & WidthInfo::VARIATION_SELECTOR_1_2_OR_3.0)
            == WidthInfo::VARIATION_SELECTOR_1_2_OR_3.0
    }

    /// Set 7th bit
    pub(crate) fn set_vs1_2_3(self) -> Self {
        if (self.0 & LIGATURE_TRANSPARENT_MASK) == LIGATURE_TRANSPARENT_MASK {
            Self(
                self.0
                    | WidthInfo::VARIATION_SELECTOR_1_2_OR_3.0
                        & !WidthInfo::VARIATION_SELECTOR_15.0
                        & !WidthInfo::VARIATION_SELECTOR_16.0,
            )
        } else {
            Self(WidthInfo::VARIATION_SELECTOR_1_2_OR_3.0)
        }
    }

    /// Clear 7th bit
    pub(crate) fn unset_vs1_2_3(self) -> Self {
        Self(self.0 & !WidthInfo::VARIATION_SELECTOR_1_2_OR_3.0)
    }
}
